### PR TITLE
Testing solution for issue #195

### PR DESCRIPTION
**Pull request by devendragovil**
Trying a way to resolve the datasets issue #195. Will need to raise a PR for this to test out the solution

### CODE REVIEW

**Comment by ffl096** [comment]
I am not experienced with `setuptools` and thus cannot comment on the right approach here. Removing me as reviewer here :)

**Comment by devendragovil** [comment]
@mhajij  This PR is not ready yet. 

I initially raised this PR so as to be able to test my solutions. Converting this to draft for now.

**Review by mhajij — APPROVED** [review]

**Comment by ffl096** [comment]
@mhajij did you mean to close this?

**Comment by mhajij** [comment]
> @mhajij did you mean to close this?

@ffl096, I reopened it.

**Comment by ffl096** [comment]
`setuptools-scm` has been added to the build process with #381.

**Pull request closed without merging**
