### PR TITLE
adding 4 test cases for simplicial complex

### PR DESCRIPTION
**Pull request by gurug-dev**
[First contribution]

adding few test cases to simplicial complex

1. test case TypeError if Simplices is not Iterable type during init.
2. test case shape property when Simplicial Complex is empty.
3. test case for __str__ method
4. test case for KeyError for non-exisitent simplex in getitem

### CODE REVIEW

**Comment by gurug-dev** [comment]
@mhajij added a few test cases for Simplicial Complex, tagging for visibility

**Comment by mhajij** [comment]
@ninamiolane I am not sure why Docs fails here, can you please explain?

**Comment by ffl096** [comment]
> @ninamiolane I am not sure why Docs fails here, can you please explain?

#113 is the cause for this. Essentially any pull request originating from a forked repository fails currently. There is nothing wrong with this pull request (regarding the docs workflow).

**Comment by mhajij** [comment]
ok I will merge then. Thanks!

**Review by mhajij — APPROVED** [review]

**Pull request merged**
